
public class Problem_45 {
	
	/* Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
	 * 
	 * Triangle Tn=n(n+1)/2 1, 3, 6, 10, 15, ... Pentagonal Pn=n(3n−1)/2 1, 5, 12, 22, 35, ... Hexagonal
	 * Hn=n(2n−1) 1, 6, 15, 28, 45, ... It can be verified that T285 = P165 = H143 = 40755.
	 * 
	 * Find the next triangle number that is also pentagonal and hexagonal. */
	public static void main(String[] args) {
		long answer = 0;
		int i = 143;
		while (answer == 0) {
			i++;
			System.out.println(i);
			if (Funcs.isShapeNum(Funcs.getNShapeNum(i, 6)).contains(5)) answer = Funcs.getNShapeNum(i, 6);
		}
		System.out.println(answer);
	}
}
