
public class Problem_44 {
	
	/* Pentagonal numbers are generated by the formula, Pn>=n(3n−1)/2. The first ten
	 * pentagonal numbers are:
	 * 
	 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
	 * 
	 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not
	 * pentagonal.
	 * 
	 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal
	 * and D = |Pk − Pj| is minimised; what is the value of D? */
	public static void main(String[] args) {
		long answer = 0;
		int i = 0;
		while(answer==0){
			i++;
			long p1 = Funcs.getNShapeNum(i, 5);
			for (int j = 1;j < i;j++) {
				long p2 = Funcs.getNShapeNum(j, 5);
				if (Funcs.isShapeNum(p1 - p2).contains(5) && Funcs.isShapeNum(p1 + p2).contains(5)) answer = p1 - p2;
			}
		}
		System.out.println(answer);
	}
	
}
